Create an implementation of a generic list #2
jakejack13/sos pull request #26
Opened 2022-11-30 02:53 UTC by Altanis

Addresses issue #2.

Modified `struct list` in `list.h` to reflect the new changes to how the list will be structured. Modified `list.c` to create all the necessary functions.

- [ ] I have tested my code and proven it works.

2022-11-30 03:20 UTC, Altanis8593 approved these changes, later dismissed
As a user of this operating system since the summer, I have been anxiously waiting for the generic list to come out to further expand my currently limited usage of this OS. I truly believe that this change brought to the repository has tremendous potential and I'd love to see you contribute again to furthermore improve the overall usability of this operating system. You are an Inspiration, Altanis.

2022-12-12 18:06 UTC, jakejack13 requested changes
Looking good as a first draft. Just a couple minor changes needed.

2022-12-12 18:06 UTC, jakejack13 commented on include/lib/list.h
> +    struct node* next;
You should name this something like `head` instead of `next` to prevent confusion with `node.next`

2022-12-12 18:06 UTC, jakejack13 commented on include/lib/list.h
> +    struct node* next;
You should name this something like `head` instead of `next` to prevent confusion with `node.next`

2022-12-12 18:06 UTC, jakejack13 commented on src/lib/list.c
> +        free(n->data);
You should not free the data since you should just be emptying the list of its elements. Reasons for not freeing: a) client still wants to further use the items and has references pointing to them to free later, or b) the items were never allocated on the heap and so this will be undefined behavior.

2022-12-12 18:59 UTC, jakejack13 requested changes
Change the style back please

2022-12-12 18:59 UTC, jakejack13 commented on include/lib/list.h
> +void list_init(struct list* l);
Why. Just make it match with the rest of the style

2022-12-20 02:19 UTC, jakejack13 approved these changes
Looks good

2022-12-20 02:20 UTC, merged